//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_photo_duval.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilite
    {
        public int Photographe_ID { get; set; }
        public System.DateTime DateDebutDisponibilite { get; set; }
        public System.DateTime DateFinDisponibilite { get; set; }
    
        public virtual Photographe Photographe { get; set; }
    }
}
