//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_photo_duval.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hist_Seance
    {
        public int Hist_Seance_ID { get; set; }
        public int Seance_ID { get; set; }
        public int Photographe_ID { get; set; }
        public int Agent_ID { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string Statut { get; set; }
        public System.DateTime DateSeance { get; set; }
        public Nullable<System.DateTime> DateFinSeance { get; set; }
        public System.DateTime DateHistSeance { get; set; }
    }
}
