//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using static projet_photo_duval.MetaData.Photo;

namespace projet_photo_duval.Models
{
    [MetadataType(typeof(PhotoMetaData))]
    public partial class Photo
    {
        public int Photo_ID { get; set; }
        public byte[] Photo1 { get; set; }
        public int Seance_ID { get; set; }
        public string Nom { get; set; }
        public string Commentaire { get; set; }
    
        public virtual Seance Seance { get; set; }
    }
}
